NAME = rush-02

FLAGS = -Wall -Werror -Wextra

SRCS = ft_atoi.c ft_count.c ft_findsft.c ft_nbr2str.c ft_print.c ft_checkdictionary.c main.c

all: $(NAME)

$(NAME):
		cc $(FLAGS) -o $(NAME) $(SRCS)

fclean:
		rm -f $(NAME)